# If you don't include the --platform it will build as if it's
# for the M1 chip which is not what we use on container services.
FROM --platform=linux/amd64 jupyter/minimal-notebook
# Set the working directory
WORKDIR /workspace/
# Make port 8888 available to the world outside this container
EXPOSE 8888
# Copy the notebooks directory to the container's /app directory
RUN mkdir /workspace/.local /workspace/.cache && chmod 777 -R /workspace
# Run Jupyter Lab on port 8888 when the container launches
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
