site_name: Daniel Wilczak - Tutorials
repo_url: https://github.com/sfc-gh-dwilczak/tutorials/

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav:
  - Snowflake:
    - Getting Started: index.md
    - Storage buckets:
      - AWS: snowflake/aws/readme.md
      - Azure: snowflake/azure/readme.md
      - GCP: snowflake/gcp/readme.md
      - SFTP: snowflake/sftp/setup.md
    - Jupyter Notebook:
      - Basics: snowflake/jupyter/basics.md
      - ML Model: snowflake/jupyter/models.md
    - Container Services:
      - CPU Jupyter Notebook: snowflake/container/cpu_jupyter.md
      - GPU Jupyter Notebook: snowflake/container/gpu_jupyter.md
    - Connection:
      - JDBC: snowflake/connection/jdbc.md
      - R: snowflake/connection/r.md
    - Versions:
      - Trial: snowflake/versions/trial.md
      - On-demand: snowflake/versions/on_demand.md
      - Capacity: snowflake/versions/capacity.md
  - Fivetran:
      - Setup: snowflake/fivetran/setup.md
      - Databases:
        - RDS Postgres: snowflake/fivetran/rds_postgres.md
        - RDS SQL Server: snowflake/fivetran/rds_sql_server.md
  - DBT:
    - Cloud:
      - Setup: dbt/cloud.md
    - Core: 
      - Setup: dbt/core.md
  - Github:
    - Github Docs: github/docs.md
  - Okta:
    - Snowflake: okta/snowflake.md


markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Icons
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true 

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

