site_name: Tutorials
repo_url: https://github.com/sfc-gh-dwilczak/tutorials/

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Snowflake:
    - Storage bucket: 
      - AWS: snowflake/aws/readme.md
      - Azure: snowflake/azure/readme.md
      - GCP: snowflake/gcp/readme.md
    - Jupyter Notebok:
      - Basics: snowflake/jupyter/basics.md
      - ML Model: snowflake/jupyter/ml_models.md
    - Connection:
      - JDBC: snowflake/connection/jdbc.md
      - R: snowflake/connection/r.md
  - Fivetran:
    - RDS Postgres: snowflake/fivetran/rds_postgres.md
    - RDS SQL Server: snowflake/fivetran/rds_sql_server.md
  - Github:
    - Github Docs: github/docs.md
  - Okta:
    - Snowflake: okta/snowflake.md
    
  
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Icons
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true 

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'