FROM --platform=linux/amd64 python:3.11

WORKDIR /app

# Copy the requirements file.
COPY ./requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Add the templates folde to the image
COPY ./templates /app/templates

# Copy the rest of your application
COPY ./ /app

EXPOSE 8080

ENV FLASK_APP = app
CMD ["python3", "app.py"]
